var ZoneProperties = {
Newcastle: {type: "land", owner:"uk"},
Oslo: {type: "land", owner:""},
Denmark: {type: "land", owner:""},
Glascow: {type: "land", owner:"uk"},
Ireland: {type: "land", owner:""},
Belgium: {type: "land", owner:""},
Paris: {type: "land", owner:"fr"},
LeMans: {type: "land", owner:"fr"},
Hamburg: {type: "land", owner:"de"},
Munich: {type: "land", owner:"de"},
Berlin: {type: "land", owner:"de"},
Frankfurt: {type: "land", owner:"de"},
Konigsberg: {type: "land", owner:"de"},
Stettin: {type: "land", owner: "de"},
Switzerland: {type: "land", owner: ""},
Bergen: {type: "land", owner:""},
Danzig: {type: "land", owner:""},
Trondheim: {type: "land", owner:""},
Brest: {type: "land", owner:"fr"},
Calais: {type: "land", owner:"fr"},
Orleans: {type: "land", owner:"fr"},
Nancy: {type: "land", owner:"fr"},
Casablanca: {type: "land", owner: "fr"},
London: {type: "land", owner:"uk"},
Bristol: {type: "land", owner:"uk"},
Koln: {type: "land", owner: "de"},
Manchester: {type: "land", owner:"uk"},
Netherlands: {type: "land", owner:""},
Belfast: {type: "land", owner:"uk"},
Venice: {type: "land", owner: "it"},
Milan: {type: "land", owner: "it"},
Florence: {type: "land", owner: "it"},
Rome: {type: "land", owner: "it"},
Lithuania: {type: "land", owner: "buffer"},
Moscow: {type: "land", owner: "ru"},
DenmarkSeazone: {type: "sea"},
NorthernNorthSea: {type: "sea"},
IrishSea: {type: "sea"},
ScapaFlow: {type: "sea"},
WesternAtlantic: {type: "sea"},
BrestHarbor: {type: "sea"},
HamburgHarbor: {type: "sea"},
BergenCoast: {type: "sea"},
TrondheimHarbor: {type: "sea"},
EnglishEasternCoast: {type: "sea"},
EasternEnglishChannel: {type: "sea"},
WesternEnglishChannel: {type: "sea"},
BristolHarbor: {type: "sea"},
Seazone8: {type: "sea"},
Seazone3: {type: "sea"},
Seazone4: {type: "sea"},
Seazone10: {type: "sea"},
BayofBiscay: {type: "sea"},
WesternBaltic: {type: "sea"},
CentralBaltic: {type: "sea"},
CorsicaSeazone: {type: "sea"},
MarseilleHarbor: {type: "sea"},
CentralWesternMed: {type: "sea"},
BarcelonaHarbor: {type: "sea"},
AlgeriaEastCoast: {type: "sea"},
AlgeriaCentralCoast: {type: "sea"},
AlgeriaWestCoast: {type: "sea"},
GibralterHarbor: {type: "sea"},
SicilyNorthCoast: {type: "sea"},
NorthAdriatic: {type: "sea"}
};
