var ZoneProperties = {
Newcastle: {type: "land", owner:"uk"},
Oslo: {type: "land", owner:"nr"},
Denmark: {type: "land", owner:"dk"},
Glascow: {type: "land", owner:"uk"},
Ireland: {type: "land", owner:"ir"},
Belgium: {type: "land", owner:"be"},
Paris: {type: "land", owner:"fr"},
LeMans: {type: "land", owner:"fr"},
Hamburg: {type: "land", owner:"de"},
Munich: {type: "land", owner:"de"},
Berlin: {type: "land", owner:"de"},
Frankfurt: {type: "land", owner:"de"},
Konigsberg: {type: "land", owner:"de"},
Stettin: {type: "land", owner: "de"},
Switzerland: {type: "land", owner: "sz"},
Bergen: {type: "land", owner:"po"},
Danzig: {type: "land", owner:"po"},
Warsaw: {type: "land", owner: "po"},
Trondheim: {type: "land", owner:"nr"},
Rhodes: {type: "land", owner:"gr"},
Athens: {type: "land", owner: "gr"},
Crete: {type: "land", owner: "gr"},
Volos: {type: "land", owner: "gr"},
Baghdad: {type: "land", owner: "iq"},
Mosul: {type: "land", owner: "iq"},
Basra: {type: "land", owner: "iq"},
Brest: {type: "land", owner:"fr"},
Calais: {type: "land", owner:"fr"},
Orleans: {type: "land", owner:"fr"},
Nancy: {type: "land", owner:"fr"},
Casablanca: {type: "land", owner: "fr"},
Corsica: {type: "land", owner: "fr"},
Aleppo: {type: "land", owner: "fr"},
Beirut: {type: "land", owner: "fr"},
Tunis: {type: "land", owner: "fr"},
London: {type: "land", owner:"uk"},
Bristol: {type: "land", owner:"uk"},
Koln: {type: "land", owner: "de"},
Manchester: {type: "land", owner:"uk"},
Netherlands: {type: "land", owner:"ne"},
Belfast: {type: "land", owner:"uk"},
Malta: {type: "land", owner: "uk"},
Alexandria: {type: "land", owner: "uk"},
Suez: {type: "land", owner: "uk"},
Cairo: {type: "land", owner: "uk"},
Kuwait: {type: "land", owner: "uk"},
Cyprus: {type: "land", owner: "uk"},
Jaffa: {type: "land", owner: "uk"},
Amman: {type: "land", owner: "uk"},
Gibralter: {type: "land", owner: "uk"},
ElAlamein: {type: "land", owner: "uk"},
Venice: {type: "land", owner: "it"},
Milan: {type: "land", owner: "it"},
Florence: {type: "land", owner: "it"},
Albania: {type: "land", owner: "it"},
Naples: {type: "land", owner: "it"},
Rome: {type: "land", owner: "it"},
Sicily: {type: "land", owner: "it"},
Taranto: {type: "land", owner: "it"},
Sardinia: {type: "land", owner: "it"},
Tripoli: {type: "land", owner: "it"},
Lithuania: {type: "land", owner: "buffer"},
Latvia: {type: "land", owner: "buffer"},
Estonia: {type: "land", owner: "buffer"},
Pinsk: {type: "land", owner: "buffer"},
Wilno: {type: "land", owner: "buffer"},
Minsk: {type: "land", owner: "ru"},
Moscow: {type: "land", owner: "ru"},
Leningrad: {type: "land", owner: "ru"},
Sevastapol: {type: "land", owner: "ru"},
Baku: {type: "land", owner: "ru"},
Istanbul: {type: "land", owner: "tr"},
Ankara: {type: "land", owner: "tr"},
SevastapolHarbor: {type: "sea"},
DenmarkSeazone: {type: "sea"},
NorthernNorthSea: {type: "sea"},
IrishSea: {type: "sea"},
ScapaFlow: {type: "sea"},
WesternAtlantic: {type: "sea"},
BrestHarbor: {type: "sea"},
HamburgHarbor: {type: "sea"},
BergenCoast: {type: "sea"},
TrondheimHarbor: {type: "sea"},
EnglishEasternCoast: {type: "sea"},
EasternEnglishChannel: {type: "sea"},
WesternEnglishChannel: {type: "sea"},
BristolHarbor: {type: "sea"},
Seazone8: {type: "sea"},
Seazone3: {type: "sea"},
Seazone4: {type: "sea"},
Seazone10: {type: "sea"},
BayofBiscay: {type: "sea"},
WesternBaltic: {type: "sea"},
CentralBaltic: {type: "sea"},
CorsicaSeazone: {type: "sea"},
MarseilleHarbor: {type: "sea"},
CentralWesternMed: {type: "sea"},
BarcelonaHarbor: {type: "sea"},
AlgeriaEastCoast: {type: "sea"},
AlgeriaCentralCoast: {type: "sea"},
AlgeriaWestCoast: {type: "sea"},
GibralterHarbor: {type: "sea"},
SicilyNorthCoast: {type: "sea"},
NorthAdriatic: {type: "sea"},
SouthAdriatic: {type: "sea"},
MaltaSeazone: {type: "sea"},
TarantoHarbor: {type: "sea"},
CentralMed: {type: "sea"},
TunisianCoast: {type: "sea"},
GreeceWestcoast: {type: "sea"},
TripoliCoast: {type: "sea"},
LeningradHarbor: {type: "sea"},
NorthernBaltic: {type: "sea"},
EgyptWestCoast: {type: "sea"},
TobrukCoast: {type: "sea"},
LibyaEastCoast: {type: "sea"},
AlexandriaHarbor: {type: "sea"},
BeirutCoast: {type: "sea"},
AleppoCoast: {type: "sea"},
EasternMed: {type: "sea"},
AthensHarbor: {type: "sea"},
IstanbulHarbor: {type: "sea"},
WesternBlackSea: {type: "sea"},
EasternBlackSea: {type: "sea"},
RedSea: {type: "sea"}
};
