var ZoneProperties = {
/** Norway **/
Oslo: {type: "land", owner:"nr", hasFactory: true, pointValue: 1},
Trondheim: {type: "land", owner:"nr", hasFactory: true, pointValue: 1},
Bergen: {type: "land", owner:"nr", hasFactory: true, pointValue: 1},
/** Finland **/
Helsinki: {type: "land", owner:"fn", hasFactory: true, pointValue: 2},
Tampere: {type: "land", owner:"fn", hasFactory: true, pointValue: 1},
Kuopio: {type: "land", owner:"fn", hasFactory: false, pointValue: 0},
/** Hungary **/
Budapest: {type: "land", owner:"hu", hasFactory: true, pointValue: 2},
Debrecen: {type: "land", owner:"hu", hasFactory: true, pointValue: 1},
/** Bulgaria **/
Sofia: {type: "land", owner:"bu", hasFactory: true, pointValue: 2},
Varna: {type: "land", owner:"bu", hasFactory: false, pointValue: 0},
Burgas: {type: "land", owner: "bu", hasFactory: true, pointValue: 1},
/** Single-Zone Neutrals **/
Denmark: {type: "land", owner:"dk", hasFactory: true, pointValue: 1},
Ireland: {type: "land", owner:"ir", hasFactory: true, pointValue: 1},
Belgium: {type: "land", owner:"be", hasFactory: true, pointValue: 2},
Netherlands: {type: "land", owner:"ne", hasFactory: true, pointValue: 1},
Switzerland: {type: "land", owner: "sz", hasFactory: true, pointValue: 3},
/** Germany **/
Hamburg: {type: "land", owner:"de", hasFactory: true, pointValue: 3},
Munich: {type: "land", owner:"de", hasFactory: true, pointValue: 4},
Berlin: {type: "land", owner:"de", hasFactory: true, pointValue: 2},
Frankfurt: {type: "land", owner:"de", hasFactory: true, pointValue: 6},
Konigsberg: {type: "land", owner:"de", hasFactory: true, pointValue: 1},
Stettin: {type: "land", owner: "de", hasFactory: true, pointValue: 2},
Koln: {type: "land", owner: "de", hasFactory: true, pointValue: 5},
Breslau: {type: "land", owner: "de", hasFactory: true, pointValue: 3},
Leipzig: {type: "land", owner: "de", hasFactory: true, pointValue: 3},
Wien: {type: "land", owner: "de", hasFactory: true, pointValue: 3},
Praha: {type: "land", owner: "de", hasFactory: true, pointValue: 3},
Presov: {type: "land", owner: "de", hasFactory: true, pointValue: 4},
/** Sweden **/
Goteborg: {type: "land", owner: "sw", hasFactory: true, pointValue: 3},
Stockholm: {type: "land", owner: "sw", hasFactory: true, pointValue: 2},
Soderhamn: {type: "land", owner: "sw", hasFactory: true, pointValue: 2},
Sundsvall: {type: "land", owner: "sw", hasFactory: true, pointValue: 1},
/** Poland **/
Danzig: {type: "land", owner:"po", hasFactory: true, pointValue: 1},
Warsaw: {type: "land", owner: "po", hasFactory: true, pointValue: 2},
Posen: {type: "land", owner: "po", hasFactory: true, pointValue: 1},
Krakow: {type: "land", owner: "po", hasFactory: false, pointValue: 0},
/** Greece **/
Rhodes: {type: "land", owner:"gr", hasFactory: false, pointValue: 0},
Athens: {type: "land", owner: "gr", hasFactory: true, pointValue: 2},
Crete: {type: "land", owner: "gr", hasFactory: false, pointValue: 0},
Volos: {type: "land", owner: "gr", hasFactory: true, pointValue: 1},
Thessalonika: {type: "land", owner: "gr", hasFactory: true, pointValue: 1},
/** Yugoslavia **/
Zagreb: {type: "land", owner: "yu", hasFactory: true, pointValue: 1},
Beograd: {type: "land", owner: "yu", hasFactory: true, pointValue: 2},
Nis: {type: "land", owner: "yu", hasFactory: true, pointValue: 1},
Bitolji: {type: "land", owner: "yu", hasFactory: true, pointValue: 1},
Nis: {type: "land", owner: "yu", hasFactory: false, pointValue: 0},
Mostar: {type: "land", owner: "yu", hasFactory: false, pointValue: 0},
/** Iraq **/
Baghdad: {type: "land", owner: "iq", hasFactory: true, pointValue: 1},
Mosul: {type: "land", owner: "iq", hasFactory: false, pointValue: 0},
Basra: {type: "land", owner: "iq", hasFactory: true, pointValue: 2},
/** France **/
Paris: {type: "land", owner:"fr", hasFactory: true, pointValue: 2},
LeMans: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Brest: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Calais: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Orleans: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Nancy: {type: "land", owner:"fr", hasFactory: true, pointValue: 5},
Reims: {type: "land", owner:"fr", hasFactory: true, pointValue: 4},
Bordeaux: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Clermont: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Toulouse: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Lyon: {type: "land", owner:"fr", hasFactory: true, pointValue: 2},
Marseille: {type: "land", owner:"fr", hasFactory: true, pointValue: 1},
Rabat: {type: "land", owner: "fr", hasFactory: true, pointValue: 1},
Oudja: {type: "land", owner: "fr", hasFactory: false, pointValue: 0},
Bone: {type: "land", owner: "fr", hasFactory: false, pointValue: 0},
Gabes: {type: "land", owner: "fr", hasFactory: false, pointValue: 0},
Touggourt: {type: "land", owner: "fr", hasFactory: false, pointValue: 0},
Oran: {type: "land", owner: "fr", hasFactory: false, pointValue: 0},
Algiers: {type: "land", owner: "fr", hasFactory: true, pointValue: 1},
Corsica: {type: "land", owner: "fr"},
Aleppo: {type: "land", owner: "fr"},
Beirut: {type: "land", owner: "fr"},
Tunis: {type: "land", owner: "fr"},
/** United Kingdom **/
Manchester: {type: "land", owner:"uk"},
Glascow: {type: "land", owner:"uk"},
London: {type: "land", owner:"uk"},
Bristol: {type: "land", owner:"uk"},
Newcastle: {type: "land", owner:"uk", hasFactory: true, pointValue: 6},
Belfast: {type: "land", owner:"uk"},
Malta: {type: "land", owner: "uk"},
Alexandria: {type: "land", owner: "uk"},
Suez: {type: "land", owner: "uk"},
Cairo: {type: "land", owner: "uk"},
Kuwait: {type: "land", owner: "uk"},
Cyprus: {type: "land", owner: "uk"},
Jaffa: {type: "land", owner: "uk"},
Amman: {type: "land", owner: "uk"},
Gibralter: {type: "land", owner: "uk"},
ElAlamein: {type: "land", owner: "uk"},
Sallum: {type: "land", owner: "uk", hasFactory: false, pointValue: 0},
/** Spain **/
Spanish_Morocco: {type: "land", owner: "sp", hasFactory: false, pointValue: 0},
Bilbao: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Barcelona: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Granada: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Valencia: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Madrid: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Sevilla: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Cordoba: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Salamanca: {type: "land", owner: "sp", hasFactory: true, pointValue: 1},
Gijon: {type: "land", owner: "sp", hasFactory: false, pointValue: 0},
/** Portugal **/
Porto: {type: "land", owner: "pr", hasFactory: true, pointValue: 1},
Lisbon: {type: "land", owner: "pr", hasFactory: true, pointValue: 1},
/** Italy **/
Venice: {type: "land", owner: "it"},
Milan: {type: "land", owner: "it"},
Florence: {type: "land", owner: "it"},
Albania: {type: "land", owner: "it"},
Naples: {type: "land", owner: "it"},
Rome: {type: "land", owner: "it"},
Sicily: {type: "land", owner: "it"},
Taranto: {type: "land", owner: "it"},
Sardinia: {type: "land", owner: "it"},
Tripoli: {type: "land", owner: "it"},
Sirte: {type: "land", owner: "it", hasFactory: false, pointValue: 0},
Benghazi: {type: "land", owner: "it", hasFactory: false, pointValue: 0},
Tubruq: {type: "land", owner: "it", hasFactory: false, pointValue: 0},
/** Soviet Occupied Buffer Zones **/
Lithuania: {type: "land", owner: "buffer"},
Latvia: {type: "land", owner: "buffer"},
Estonia: {type: "land", owner: "buffer"},
Pinsk: {type: "land", owner: "buffer"},
Wilno: {type: "land", owner: "buffer"},
Bjorko: {type: "land", owner: "buffer"},
Chisinau: {type: "land", owner: "buffer", hasFactory: false, pointValue: 0},
/** USSR **/
Minsk: {type: "land", owner: "ru"},
Moscow: {type: "land", owner: "ru"},
Leningrad: {type: "land", owner: "ru"},
Sevastapol: {type: "land", owner: "ru"},
Baku: {type: "land", owner: "ru"},
Olonets: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Novgorod: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Zabore: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Tbilisi: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Poti: {type: "land", owner: "ru", hasFactory: true, pointValue: 1},
Krasnodar: {type: "land", owner: "ru", hasFactory: true, pointValue: 1},
Rostov: {type: "land", owner: "ru", hasFactory: true, pointValue: 1},
Dnepropetrovsk: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Yemtsa: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Vologda: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Velsk: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Toropets: {type: "land", owner: "ru", hasFactory: false, pointValue: 0},
Odessa: {type: "land", owner: "ru", hasFactory: true, pointValue: 1},
Yaroslavl: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Ryazan: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Tula: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Kharkov: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Kargopol: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Tver: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Rzhev: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Kaluga: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
Smolensk: {type: "land", owner: "ru", hasFactory: false, pointValue : 0},
/** Romania **/
Galati: {type: "land", owner: "rm", hasFactory: false, pointValue: 0},

/** Turkey **/
Istanbul: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
Ankara: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
Izmir: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
Izmit: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
Adana: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
Selinoi: {type: "land", owner: "tr", hasFactory: false, pointValue: 0},
Konya: {type: "land", owner: "tr", hasFactory: false, pointValue: 0},
Mugla: {type: "land", owner: "tr", hasFactory: true, pointValue: 1},
/** Ocean **/
SevastapolHarbor: {type: "sea"},
DenmarkSeazone: {type: "sea"},
NorthernNorthSea: {type: "sea"},
IrishSea: {type: "sea"},
ScapaFlow: {type: "sea"},
WesternAtlantic: {type: "sea"},
BrestHarbor: {type: "sea"},
HamburgHarbor: {type: "sea"},
BergenCoast: {type: "sea"},
TrondheimHarbor: {type: "sea"},
EnglishEasternCoast: {type: "sea"},
EasternEnglishChannel: {type: "sea"},
WesternEnglishChannel: {type: "sea"},
BristolHarbor: {type: "sea"},
Seazone8: {type: "sea"},
Seazone3: {type: "sea"},
Seazone4: {type: "sea"},
Seazone10: {type: "sea"},
BayofBiscay: {type: "sea"},
WesternBaltic: {type: "sea"},
CentralBaltic: {type: "sea"},
CorsicaSeazone: {type: "sea"},
MarseilleHarbor: {type: "sea"},
CentralWesternMed: {type: "sea"},
BarcelonaHarbor: {type: "sea"},
AlgeriaEastCoast: {type: "sea"},
AlgeriaCentralCoast: {type: "sea"},
AlgeriaWestCoast: {type: "sea"},
GibralterHarbor: {type: "sea"},
SicilyNorthCoast: {type: "sea"},
NorthAdriatic: {type: "sea"},
SouthAdriatic: {type: "sea"},
MaltaSeazone: {type: "sea"},
TarantoHarbor: {type: "sea"},
CentralMed: {type: "sea"},
TunisianCoast: {type: "sea"},
GreeceWestcoast: {type: "sea"},
TripoliCoast: {type: "sea"},
LeningradHarbor: {type: "sea"},
NorthernBaltic: {type: "sea"},
EgyptWestCoast: {type: "sea"},
TobrukCoast: {type: "sea"},
LibyaEastCoast: {type: "sea"},
AlexandriaHarbor: {type: "sea"},
BeirutCoast: {type: "sea"},
AleppoCoast: {type: "sea"},
EasternMed: {type: "sea"},
AthensHarbor: {type: "sea"},
IstanbulHarbor: {type: "sea"},
WesternBlackSea: {type: "sea"},
EasternBlackSea: {type: "sea"},
RedSea: {type: "sea"},
LeningradLake: {type: "sea"}
};
